#!/bin/bash

#
# Checkout or update forumlas
#
SCRIPT_PATH="$0"
while [ -h "$SCRIPT_PATH" ]
do
  SCRIPT_PATH=`readlink -f "$SCRIPT_PATH"`
done

EXEC_PATH="`pwd -P`"
cd `dirname "$SCRIPT_PATH"`
SCRIPT_DIR="`pwd -P`"

cd ../salt/formulas

for entry in `cat repos.list | sed '/\#.*/d' | sed '/^\s*$/d'`
do
  repo_dir=`echo ${entry#*/} | sed 's/\.git$//'`
  if [ ! -e $repo_dir ]
  then
    echo "Cloning ${repo_dir} ..."
    git clone $entry
  else
    echo -n "Updating ${repo_dir} ... "
    cd $repo_dir
    git pull --rebase
    cd ..
  fi
done